
CREATE TABLE LOCATION (
                ID_LOCATION INTEGER NOT NULL,
                CITY_NAME VARCHAR(200) NOT NULL,
                ID_PROVINCE INTEGER,
                CONSTRAINT ID_LOCATION PRIMARY KEY (ID_LOCATION)
);


CREATE TABLE INTERVIEW_CUSTOMERS (
                ID_INTERVIEWS_CUSTOMER_PK INTEGER NOT NULL,
                ID_LOCATION INTEGER NOT NULL,
                LINK VARCHAR(500) NOT NULL,
                Q1 VARCHAR(150),
                Q2 VARCHAR(150),
                Q3 VARCHAR(150),
                Q4 VARCHAR(150),
                Q5 VARCHAR(150),
                Q6 VARCHAR(150),
                Q7 VARCHAR(150),
                Q8 VARCHAR(150),
                Q9 VARCHAR(150),
                Q10 VARCHAR(150),
                Q11 VARCHAR(150),
                Q12 VARCHAR(150),
                Q13 VARCHAR(150),
                Q14 VARCHAR(150),
                Q15 VARCHAR(150),
                Q16 VARCHAR(150),
                Q17 VARCHAR(150),
                Q18 VARCHAR(150),
                Q19 VARCHAR(150),
                Q20 VARCHAR(150),
                Q21 VARCHAR(150),
                Q22 VARCHAR(150),
                Q23 VARCHAR(150),
                Q24 VARCHAR(150),
                CONSTRAINT ID_INTERVIEWS_CUSTOMER_PK PRIMARY KEY (ID_INTERVIEWS_CUSTOMER_PK, ID_LOCATION)
);


CREATE TABLE INTERVIEW_VENDORS (
                ID_INTERVIEWS_VENDOR_PK INTEGER NOT NULL,
                ID_LOCATION INTEGER NOT NULL,
                LINK VARCHAR(500) NOT NULL,
                Q1 VARCHAR(150),
                Q2 VARCHAR(150),
                Q3 VARCHAR(150),
                Q4 VARCHAR(150),
                Q5 VARCHAR(150),
                Q6 VARCHAR(150),
                Q7 VARCHAR(150),
                Q8 VARCHAR(150),
                Q9 VARCHAR(150),
                Q10 VARCHAR(150),
                Q11 VARCHAR(150),
                Q12 VARCHAR(150),
                Q13 VARCHAR(150),
                Q14 VARCHAR(150),
                Q15 VARCHAR(150),
                Q16 VARCHAR(150),
                Q17 VARCHAR(150),
                Q18 VARCHAR(150),
                Q19 VARCHAR(150),
                Q20 VARCHAR(150),
                Q21 VARCHAR(150),
                Q22 VARCHAR(150),
                Q23 VARCHAR(150),
                CONSTRAINT ID_INTERVIEWS_VENDOR_PK PRIMARY KEY (ID_INTERVIEWS_VENDOR_PK, ID_LOCATION)
);


CREATE TABLE PLANTS (
                ID_PLANT_PK INTEGER NOT NULL,
                ID_LOCATION INTEGER NOT NULL,
                CURRENT_NAME VARCHAR(200) NOT NULL,
                SCIENTIFIC_NAME VARCHAR(200) NOT NULL,
                CONSTRAINT ID_PLANT_PK PRIMARY KEY (ID_PLANT_PK, ID_LOCATION)
);


CREATE TABLE PREVIOUS_RESEARCHS (
                ID_RESEARCH_PK INTEGER NOT NULL,
                ID_PLANT_PK INTEGER NOT NULL,
                TITLE VARCHAR(400) NOT NULL,
                LINK VARCHAR(400),
                CONSTRAINT ID_RESEARCH_PK PRIMARY KEY (ID_RESEARCH_PK, ID_PLANT_PK)
);


CREATE TABLE USE (
                ID_USE_PK INTEGER NOT NULL,
                ID_PLANT_PK INTEGER NOT NULL,
                DESCRIPTION VARCHAR(1750) NOT NULL,
                TYPE_USE VARCHAR(100) NOT NULL,
                CONSTRAINT ID_USE_PK PRIMARY KEY (ID_USE_PK, ID_PLANT_PK)
);


CREATE TABLE TOPONIMO (
                ID_TOPONIMO INTEGER NOT NULL,
                ID_PLANT_PK INTEGER NOT NULL,
                ORIGIN VARCHAR(250),
                COMMERCIAL_DISTRIBUTION VARCHAR(250),
                DISTRIBUTION VARCHAR(250),
                CONSTRAINT ID_TOPONIMO PRIMARY KEY (ID_TOPONIMO, ID_PLANT_PK)
);


CREATE TABLE IMAGE (
                ID_IMAGE_PK INTEGER NOT NULL,
                ID_PLANT_PK INTEGER NOT NULL,
                LINK VARCHAR(400) NOT NULL,
                DATE DATE NOT NULL,
                PLACE VARCHAR(250) NOT NULL,
                CONSTRAINT ID_IMAGE_PK PRIMARY KEY (ID_IMAGE_PK, ID_PLANT_PK)
);


ALTER TABLE PLANTS ADD CONSTRAINT LOCATION_PLANTS_fk
FOREIGN KEY (ID_LOCATION)
REFERENCES LOCATION (ID_LOCATION)
ON DELETE NO ACTION
ON UPDATE NO ACTION
NOT DEFERRABLE;

ALTER TABLE INTERVIEW_CUSTOMERS ADD CONSTRAINT LOCATION_INTERVIEW_CUSTOMERS_fk
FOREIGN KEY (ID_LOCATION)
REFERENCES LOCATION (ID_LOCATION)
ON DELETE NO ACTION
ON UPDATE NO ACTION
NOT DEFERRABLE;

ALTER TABLE INTERVIEW_VENDORS ADD CONSTRAINT LOCATION_INTERVIEW_VENDORS_fk
FOREIGN KEY (ID_LOCATION)
REFERENCES LOCATION (ID_LOCATION)
ON DELETE NO ACTION
ON UPDATE NO ACTION
NOT DEFERRABLE;

ALTER TABLE IMAGE ADD CONSTRAINT PLANTS_IMAGE_fk
FOREIGN KEY (ID_PLANT_PK)
REFERENCES PLANTS (ID_PLANT_PK)
ON DELETE NO ACTION
ON UPDATE NO ACTION
NOT DEFERRABLE;

ALTER TABLE TOPONIMO ADD CONSTRAINT PLANTS_TOPONIMO_fk
FOREIGN KEY (ID_PLANT_PK)
REFERENCES PLANTS (ID_PLANT_PK)
ON DELETE NO ACTION
ON UPDATE NO ACTION
NOT DEFERRABLE;

ALTER TABLE USE ADD CONSTRAINT PLANTS_USE_fk
FOREIGN KEY (ID_PLANT_PK)
REFERENCES PLANTS (ID_PLANT_PK)
ON DELETE NO ACTION
ON UPDATE NO ACTION
NOT DEFERRABLE;

ALTER TABLE PREVIOUS_RESEARCHS ADD CONSTRAINT PLANTS_PREVIOUS_RESEARCHS_fk
FOREIGN KEY (ID_PLANT_PK)
REFERENCES PLANTS (ID_PLANT_PK)
ON DELETE NO ACTION
ON UPDATE NO ACTION
NOT DEFERRABLE;
